### ISSUE TITLE
Traceback at line 225 (ship 15 of every crop)

### ISSUE THREAD

**Issue by ghost** [skatje-myers/stardewscripts#1]
When running your script with python3, I get a traceback at line 225:

`Missing:
Traceback (most recent call last):
  File "achievement_checker.py", line 225, in <module>
    for crop in shipped_crops:
RuntimeError: dictionary changed size during iteration
`

I looked up the error and it seems to be something with calling keys. Please fix if you can! I wanna know how many crops I need left to ship :3

**Comment by skatje-myers** [comment]
I believe it should be fixed.

**Comment by ghost** [comment]
Fantastic! That's the fix! :3
