### ISSUE TITLE
Issue with artifact_locations

### ISSUE THREAD

**Issue by Alicecold** [skatje-myers/stardewscripts#10]
When running, the following message is shown:
Traceback (most recent call last):
  File "artifact_locations.py", line 63, in <module>
    main()
  File "artifact_locations.py", line 54, in main
    if obj.find('Name').text == 'Artifact Spot':
AttributeError: 'NoneType' object has no attribute 'text'

Other information:
Playing Stardew v.1.2.33 on Windows
using Python 3.6.4

**Comment by Alicecold** [comment]
It seems that it's case-sensitive. 'Name' -> 'name' solves the problem 😄

**Comment by Alicecold** [comment]
I've fixed it in my fork. I could merge it, but I have never merged a fork before so I am unsure how to go that.

**Comment by cortl** [comment]
I fixed this in a recent pull request.  Let me know if it still doesn't work
