### ISSUE TITLE
integrating stardewscripts into upload.farm

### ISSUE THREAD

**Issue by Laukei** [skatje-myers/stardewscripts#4]
Hello! A friend and I run a website for the Stardew Valley community to render and share their savegames ([upload.farm](http://upload.farm), repository [here](https://github.com/Sketchy502/SDV-Summary)). I was looking at building in achievement planning following a [request on reddit](https://www.reddit.com/r/StardewValley/comments/60iknd/achievement_guidetool/) and saw your scripts mentioned. Would it be okay for me to modify them to work them into the site? I would be happy to link back to your repository and credit you. Let me know! Thanks!

**Comment by skatje-myers** [comment]
Sure! Just give credit somewhere.

**Comment by Laukei** [comment]
Brilliant, cheers!
